name: Deploy docs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          # Configuração de cache dos pacotes npm depende da config do Turbo Repo
          # cache: "npm"
          # cache_dependency-path: "**/package-lock.json"

      - run: npm ci

      - run: npm run build
      # Config pela vercel para cachear a aplicação
      # env:
      # TURBO_TOKEN: TOKEN CONFIGURADO
      # TURBO_TEAM: slug do team configurado na vercel

      - name: Deploy storybook
        working-directory: ./packages/docs
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
